# Generated by Django 2.0.13 on 2019-05-17 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Rol', models.IntegerField()),
                ('role_Name', models.CharField(max_length=200)),
                ('creation_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
