# Generated by Django 2.0.13 on 2019-05-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidg', '0002_auto_20190517_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsroles',
            name='id_Rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidg.Roles'),
        ),
        migrations.AlterField(
            model_name='branchsroles',
            name='id_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidg.CBranchs'),
        ),
    ]
